CREATE TABLE usuario (
  id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  nome VARCHAR(255) NULL,
  email VARCHAR(255) NULL,
  dtanasc DATE NULL,
  qtdempretimos INTEGER UNSIGNED NULL,
PRIMARY KEY(id));

CREATE TABLE livro (
  id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  titulo VARCHAR(255) NULL,
  editora VARCHAR(255) NULL,
  qtd INTEGER UNSIGNED NULL,
PRIMARY KEY(id));

CREATE TABLE emprestimo (
  id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  livro_id INTEGER UNSIGNED NOT NULL,
  usuario_id INTEGER UNSIGNED NOT NULL,
  dtaemprestimo DATE NULL,
  dtadevolucao DATE NULL,
  dtadevolvido DATE NULL,
PRIMARY KEY(id),
  FOREIGN KEY(usuario_id)
    REFERENCES usuario(id)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
  FOREIGN KEY(livro_id)
    REFERENCES livro(id)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION);